### ISSUE TITLE
ValueError: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by korakoe** [yl4579/StyleTTS2#101]
Whilst trying to load a finetuned model, i get this error
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-57-7ba835194d9d> in <cell line: 2>()
      1 start = time.time()
----> 2 wav = inference(text, ref_s, alpha=0.9, beta=0.9, diffusion_steps=20, embedding_scale=1)
      3 rtf = (time.time() - start) / (len(wav) / 24000)
      4 print(f"RTF = {rtf:5f}")
      5 import IPython.display as ipd

<ipython-input-56-ef588f1fafe6> in inference(text, ref_s, alpha, beta, diffusion_steps, embedding_scale)
     38         pred_dur = torch.round(duration.squeeze()).clamp(min=1)
     39 
---> 40         pred_aln_trg = torch.zeros(input_lengths, int(pred_dur.sum().data))
     41         c_frame = 0
     42         for i in range(pred_aln_trg.size(0)):

ValueError: cannot convert float NaN to integer
```

The model however seems completely fine during training

**Comment by yl4579** [comment]
This is probably caused by you finetuned the model but didn't finetune the diffusion model, so the style vectors after finetuning got outside the boundary of the space learned by the original diffusion model. I think you stopped before `diff_epoch` or didn't train for enough epochs after `diff_epoch`. One simple fix would be setting `alpha` or `beta` to 0 but it would generate the same output every time you run the code if the reference is the same, so I'd recommend you enable style diffusion training as well. See #81 for more discussions.
