### ISSUE TITLE
Why the Duration and Prosody Module does not work so well.

### ISSUE THREAD

**Issue by blldd** [yl4579/StyleTTS2#130]
Hi Yinghao, thank you for your great work. 
I'm trying the model trained on LibriTTS to clone a very fast-paced audio, unfortunately, the generated audio rhythm is not very fast. (I also tried to modify different parameters, like alpha, beta, diffusion_steps, embedding_scale, it still not work so well)
I was wondering is it because a Duration Module and Prosody Module does not work well, or is the rhythm of the LibriTTS dataset relatively flat?

**Comment by yl4579** [comment]
It is mostly the latter, because if you finetune the model with this particular speaker all the generated speech will be as fast as this speaker. 

The reason is if your reference is extremely fast (faster than all speakers in the LibriTTS dataset), it probably won't work. The model is quite robust at capturing the duration for those in the range of the dataset, but for those outside the range it won't work. It is one of the limitations of the model (no improvement in similarity compared to StyleTTS for OOD speaker or zero-shot speaker adaptation) and we have acknowledged this problem in the discussion of the paper. Basically we didn't design the model for zero-shot speaker adaptation and we just showed it could do this if trained on large amount of speakers (so it preserves this capability of StyleTTS). There is definitely room for improvement.
