### ISSUE TITLE
training stage 2(start joint training epoch): training will be paused and not continued

### ISSUE THREAD

**Issue by liuhuang31** [yl4579/StyleTTS2#131]
In training stage 2(start joint training epoch): when ran to 44440/50000 step, it stayed at 44440 step for nearly 6 hours and it stopped running. The GPU utilization rate was 0% for nearly 6 hours, and the CPU was not used. No machine or code issues found during inspection. The possible cause may be:

(1) Some machine or code's problem, but not found out.
(2) In China, the number 4 sometimes represents the meaning of death. When step 44440 is reached, the program dies. Hahahah, Just make a joke...

Has anyone encountered the same situation?

**Comment by yl4579** [comment]
When training with large datasets, I'd recommend you save the model regularly, like every 5000 steps instead of epochs. The epoch thing is for LJSpeech dataset. For LibriTTS I changed the code to save for every 5000 steps instead to prevent progress loss. Each epoch could take days so saving them like that is not very safe.

**Comment by liuhuang31** [comment]
Thank you so much! I will do it!
