### ISSUE TITLE
text_encoder and text_aligner are not optimized in train_second.py

### ISSUE THREAD

**Issue by stevenhillis** [yl4579/StyleTTS2#19]
I'm trying to reconcile a difference I'm seeing between the paper and the code. Figure 1a says, "joint training then follows to optimize all components except the pitch extractor". When I look at train_second.py, though, I see two components that are not being optimized: text_encoder and text_aligner. These two components are used only in no_grad contexts in train_second.py, which makes sense to me, but I wanted to check that this is correct. Thanks!

**Comment by yl4579** [comment]
Theoretically, you do need to update the text encoder and text aligner too, but in practice, I found no difference in performance between updating and not updating these two modules, probably because they were already well-trained in the first stage, so I just put them in the no_grad section to save some RAM. For fine-tuning from a base model though, you do need to update these parameters.
