### ISSUE TITLE
inference

### ISSUE THREAD

**Issue by bobo-paopao** [yl4579/StyleTTS2#22]
I used the ljspeech pre-trained model you provided for inference, and found that directly using the Inference_LJSpeech.ipynb file under the /Demo directory for generation works well. However, if I first use the compute_style function to calculate the style of the audio (data in the LJSpeech data set), then When combined, the result will be slightly less effective. I want to ask why?
![image](https://github.com/yl4579/StyleTTS2/assets/81943524/cc322f79-1267-4cfb-a5f9-0348ba9df25a)
![image](https://github.com/yl4579/StyleTTS2/assets/81943524/3cf9d28d-26e6-4b0e-87d6-56bbadb682b2)

**Comment by yl4579** [comment]
What do you mean by “less effective”? Can you share one example of synthesized examples with styles calculated from reference audio instead of sampled from the diffusion model? Surely it will sound worse than styles sampled by the diffusion model, which is exactly the point of this paper (in the ablation study section, no style diffusion produces the highest CMOS drop).
